[custom.all.tensortype]
type = "local"
path = ""
ipkg = "tensortype.ipkg"

[custom.all.tensortype-examples]
type = "local"
path = "examples"
ipkg = "tensortype-examples.ipkg"

# [custom.all.tensortype-tests]
# type = "local"
# path = "tests"
# ipkg = "tensortype-tests.ipkg"

